//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Actions/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Movement"",
            ""id"": ""800d3474-7e8c-478a-87cd-dad45a25eb2d"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""b66bf8b1-044e-4a1b-bd9c-736af8787cb8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""838b8174-9c73-424c-8c1e-75f810f94e5f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""be1d7c55-e49b-4de4-a592-66adf6bf51cc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""12ba19cb-99a9-41d7-86a8-67bbf93bb191"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9355d0e8-f064-490e-aae3-4aa9385d0f74"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7d34bfe0-efbb-4b9f-bcc1-ded8afced31f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Dialog"",
            ""id"": ""e31de894-e524-41d3-82fc-5305aa280d7b"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""2d23d0ca-5860-4d91-88dc-115f40da3dca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Continue"",
                    ""type"": ""Button"",
                    ""id"": ""97e2462f-c09c-4fb6-adc6-4f6a02fc864b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""284a4cef-c752-4ba0-9d0b-57ca6f8068b0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e8372ef-b5a2-48de-ac95-b44b13126870"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Loot"",
            ""id"": ""60cd5ea6-31e5-4473-a0bd-f86a377f3c97"",
            ""actions"": [
                {
                    ""name"": ""LootInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""d79169e5-78ef-428d-a8c9-385799a06986"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2bd12001-1973-4817-ae48-5052d24045b2"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LootInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Armoury"",
            ""id"": ""459a047b-d752-4a1f-bfdf-8b49c8c412ab"",
            ""actions"": [
                {
                    ""name"": ""AnvilInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""6087ba91-803e-46c1-a8a5-a562868f3ab2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8763a04d-0d93-443c-8c16-ca6f47901d0a"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnvilInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Infirmary"",
            ""id"": ""b0342f0d-627c-4227-81e4-4e42d918aaab"",
            ""actions"": [
                {
                    ""name"": ""FirePotInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""2e56ada7-01b6-4851-8b28-1d1215bd2767"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0506d286-97cb-4739-bacb-3d1d8421c093"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirePotInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Structure"",
            ""id"": ""f42d7c7e-ecbc-439e-a87c-54a5a1f5b973"",
            ""actions"": [
                {
                    ""name"": ""Repair"",
                    ""type"": ""Button"",
                    ""id"": ""48d4d316-80a2-4fbe-a31c-f68ef9caa70b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""33e14a96-3e59-489b-b8f3-3bbefa16a396"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Repair"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Cat"",
            ""id"": ""e627dfdf-612a-46de-8cc9-73052868e95b"",
            ""actions"": [
                {
                    ""name"": ""CollectClue"",
                    ""type"": ""Button"",
                    ""id"": ""799b4f11-3bd7-481e-b594-339e49987e33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d139f033-4691-4170-ae83-638d7568fcc6"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CollectClue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Quest"",
            ""id"": ""db2e08db-eebc-4d02-8978-9e540f491f28"",
            ""actions"": [
                {
                    ""name"": ""TakeQuest"",
                    ""type"": ""Button"",
                    ""id"": ""23d2fb28-001d-41e4-9120-7f28e7527ea9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5f053f00-5db0-46e0-9ba3-0774c80a83d0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeQuest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Sleep"",
            ""id"": ""b6147f7d-4212-4bba-9374-cf542a2ea6ad"",
            ""actions"": [
                {
                    ""name"": ""SleepToEndDay"",
                    ""type"": ""Button"",
                    ""id"": ""4b98cd7d-275f-4967-b024-33d468050a78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4cb157ea-31b6-49a7-9efa-767ca7c0de4d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SleepToEndDay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Tutorials"",
            ""id"": ""7394448b-5a1b-4b69-9344-6428a08340d9"",
            ""actions"": [
                {
                    ""name"": ""OpenTutorial"",
                    ""type"": ""Button"",
                    ""id"": ""d8019214-dce7-47a5-bc25-84065caaab14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""488aa525-857b-4e1f-9d2c-302741e95cd6"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenTutorial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Movement
        m_Movement = asset.FindActionMap("Movement", throwIfNotFound: true);
        m_Movement_Move = m_Movement.FindAction("Move", throwIfNotFound: true);
        // Dialog
        m_Dialog = asset.FindActionMap("Dialog", throwIfNotFound: true);
        m_Dialog_Interact = m_Dialog.FindAction("Interact", throwIfNotFound: true);
        m_Dialog_Continue = m_Dialog.FindAction("Continue", throwIfNotFound: true);
        // Loot
        m_Loot = asset.FindActionMap("Loot", throwIfNotFound: true);
        m_Loot_LootInteraction = m_Loot.FindAction("LootInteraction", throwIfNotFound: true);
        // Armoury
        m_Armoury = asset.FindActionMap("Armoury", throwIfNotFound: true);
        m_Armoury_AnvilInteraction = m_Armoury.FindAction("AnvilInteraction", throwIfNotFound: true);
        // Infirmary
        m_Infirmary = asset.FindActionMap("Infirmary", throwIfNotFound: true);
        m_Infirmary_FirePotInteraction = m_Infirmary.FindAction("FirePotInteraction", throwIfNotFound: true);
        // Structure
        m_Structure = asset.FindActionMap("Structure", throwIfNotFound: true);
        m_Structure_Repair = m_Structure.FindAction("Repair", throwIfNotFound: true);
        // Cat
        m_Cat = asset.FindActionMap("Cat", throwIfNotFound: true);
        m_Cat_CollectClue = m_Cat.FindAction("CollectClue", throwIfNotFound: true);
        // Quest
        m_Quest = asset.FindActionMap("Quest", throwIfNotFound: true);
        m_Quest_TakeQuest = m_Quest.FindAction("TakeQuest", throwIfNotFound: true);
        // Sleep
        m_Sleep = asset.FindActionMap("Sleep", throwIfNotFound: true);
        m_Sleep_SleepToEndDay = m_Sleep.FindAction("SleepToEndDay", throwIfNotFound: true);
        // Tutorials
        m_Tutorials = asset.FindActionMap("Tutorials", throwIfNotFound: true);
        m_Tutorials_OpenTutorial = m_Tutorials.FindAction("OpenTutorial", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movement
    private readonly InputActionMap m_Movement;
    private List<IMovementActions> m_MovementActionsCallbackInterfaces = new List<IMovementActions>();
    private readonly InputAction m_Movement_Move;
    public struct MovementActions
    {
        private @PlayerActions m_Wrapper;
        public MovementActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Movement_Move;
        public InputActionMap Get() { return m_Wrapper.m_Movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementActions set) { return set.Get(); }
        public void AddCallbacks(IMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_MovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MovementActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IMovementActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IMovementActions instance)
        {
            if (m_Wrapper.m_MovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_MovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MovementActions @Movement => new MovementActions(this);

    // Dialog
    private readonly InputActionMap m_Dialog;
    private List<IDialogActions> m_DialogActionsCallbackInterfaces = new List<IDialogActions>();
    private readonly InputAction m_Dialog_Interact;
    private readonly InputAction m_Dialog_Continue;
    public struct DialogActions
    {
        private @PlayerActions m_Wrapper;
        public DialogActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_Dialog_Interact;
        public InputAction @Continue => m_Wrapper.m_Dialog_Continue;
        public InputActionMap Get() { return m_Wrapper.m_Dialog; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DialogActions set) { return set.Get(); }
        public void AddCallbacks(IDialogActions instance)
        {
            if (instance == null || m_Wrapper.m_DialogActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DialogActionsCallbackInterfaces.Add(instance);
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Continue.started += instance.OnContinue;
            @Continue.performed += instance.OnContinue;
            @Continue.canceled += instance.OnContinue;
        }

        private void UnregisterCallbacks(IDialogActions instance)
        {
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Continue.started -= instance.OnContinue;
            @Continue.performed -= instance.OnContinue;
            @Continue.canceled -= instance.OnContinue;
        }

        public void RemoveCallbacks(IDialogActions instance)
        {
            if (m_Wrapper.m_DialogActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDialogActions instance)
        {
            foreach (var item in m_Wrapper.m_DialogActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DialogActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DialogActions @Dialog => new DialogActions(this);

    // Loot
    private readonly InputActionMap m_Loot;
    private List<ILootActions> m_LootActionsCallbackInterfaces = new List<ILootActions>();
    private readonly InputAction m_Loot_LootInteraction;
    public struct LootActions
    {
        private @PlayerActions m_Wrapper;
        public LootActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @LootInteraction => m_Wrapper.m_Loot_LootInteraction;
        public InputActionMap Get() { return m_Wrapper.m_Loot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LootActions set) { return set.Get(); }
        public void AddCallbacks(ILootActions instance)
        {
            if (instance == null || m_Wrapper.m_LootActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LootActionsCallbackInterfaces.Add(instance);
            @LootInteraction.started += instance.OnLootInteraction;
            @LootInteraction.performed += instance.OnLootInteraction;
            @LootInteraction.canceled += instance.OnLootInteraction;
        }

        private void UnregisterCallbacks(ILootActions instance)
        {
            @LootInteraction.started -= instance.OnLootInteraction;
            @LootInteraction.performed -= instance.OnLootInteraction;
            @LootInteraction.canceled -= instance.OnLootInteraction;
        }

        public void RemoveCallbacks(ILootActions instance)
        {
            if (m_Wrapper.m_LootActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILootActions instance)
        {
            foreach (var item in m_Wrapper.m_LootActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LootActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LootActions @Loot => new LootActions(this);

    // Armoury
    private readonly InputActionMap m_Armoury;
    private List<IArmouryActions> m_ArmouryActionsCallbackInterfaces = new List<IArmouryActions>();
    private readonly InputAction m_Armoury_AnvilInteraction;
    public struct ArmouryActions
    {
        private @PlayerActions m_Wrapper;
        public ArmouryActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @AnvilInteraction => m_Wrapper.m_Armoury_AnvilInteraction;
        public InputActionMap Get() { return m_Wrapper.m_Armoury; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ArmouryActions set) { return set.Get(); }
        public void AddCallbacks(IArmouryActions instance)
        {
            if (instance == null || m_Wrapper.m_ArmouryActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ArmouryActionsCallbackInterfaces.Add(instance);
            @AnvilInteraction.started += instance.OnAnvilInteraction;
            @AnvilInteraction.performed += instance.OnAnvilInteraction;
            @AnvilInteraction.canceled += instance.OnAnvilInteraction;
        }

        private void UnregisterCallbacks(IArmouryActions instance)
        {
            @AnvilInteraction.started -= instance.OnAnvilInteraction;
            @AnvilInteraction.performed -= instance.OnAnvilInteraction;
            @AnvilInteraction.canceled -= instance.OnAnvilInteraction;
        }

        public void RemoveCallbacks(IArmouryActions instance)
        {
            if (m_Wrapper.m_ArmouryActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IArmouryActions instance)
        {
            foreach (var item in m_Wrapper.m_ArmouryActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ArmouryActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ArmouryActions @Armoury => new ArmouryActions(this);

    // Infirmary
    private readonly InputActionMap m_Infirmary;
    private List<IInfirmaryActions> m_InfirmaryActionsCallbackInterfaces = new List<IInfirmaryActions>();
    private readonly InputAction m_Infirmary_FirePotInteraction;
    public struct InfirmaryActions
    {
        private @PlayerActions m_Wrapper;
        public InfirmaryActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @FirePotInteraction => m_Wrapper.m_Infirmary_FirePotInteraction;
        public InputActionMap Get() { return m_Wrapper.m_Infirmary; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InfirmaryActions set) { return set.Get(); }
        public void AddCallbacks(IInfirmaryActions instance)
        {
            if (instance == null || m_Wrapper.m_InfirmaryActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InfirmaryActionsCallbackInterfaces.Add(instance);
            @FirePotInteraction.started += instance.OnFirePotInteraction;
            @FirePotInteraction.performed += instance.OnFirePotInteraction;
            @FirePotInteraction.canceled += instance.OnFirePotInteraction;
        }

        private void UnregisterCallbacks(IInfirmaryActions instance)
        {
            @FirePotInteraction.started -= instance.OnFirePotInteraction;
            @FirePotInteraction.performed -= instance.OnFirePotInteraction;
            @FirePotInteraction.canceled -= instance.OnFirePotInteraction;
        }

        public void RemoveCallbacks(IInfirmaryActions instance)
        {
            if (m_Wrapper.m_InfirmaryActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInfirmaryActions instance)
        {
            foreach (var item in m_Wrapper.m_InfirmaryActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InfirmaryActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InfirmaryActions @Infirmary => new InfirmaryActions(this);

    // Structure
    private readonly InputActionMap m_Structure;
    private List<IStructureActions> m_StructureActionsCallbackInterfaces = new List<IStructureActions>();
    private readonly InputAction m_Structure_Repair;
    public struct StructureActions
    {
        private @PlayerActions m_Wrapper;
        public StructureActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Repair => m_Wrapper.m_Structure_Repair;
        public InputActionMap Get() { return m_Wrapper.m_Structure; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StructureActions set) { return set.Get(); }
        public void AddCallbacks(IStructureActions instance)
        {
            if (instance == null || m_Wrapper.m_StructureActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StructureActionsCallbackInterfaces.Add(instance);
            @Repair.started += instance.OnRepair;
            @Repair.performed += instance.OnRepair;
            @Repair.canceled += instance.OnRepair;
        }

        private void UnregisterCallbacks(IStructureActions instance)
        {
            @Repair.started -= instance.OnRepair;
            @Repair.performed -= instance.OnRepair;
            @Repair.canceled -= instance.OnRepair;
        }

        public void RemoveCallbacks(IStructureActions instance)
        {
            if (m_Wrapper.m_StructureActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IStructureActions instance)
        {
            foreach (var item in m_Wrapper.m_StructureActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StructureActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public StructureActions @Structure => new StructureActions(this);

    // Cat
    private readonly InputActionMap m_Cat;
    private List<ICatActions> m_CatActionsCallbackInterfaces = new List<ICatActions>();
    private readonly InputAction m_Cat_CollectClue;
    public struct CatActions
    {
        private @PlayerActions m_Wrapper;
        public CatActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @CollectClue => m_Wrapper.m_Cat_CollectClue;
        public InputActionMap Get() { return m_Wrapper.m_Cat; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CatActions set) { return set.Get(); }
        public void AddCallbacks(ICatActions instance)
        {
            if (instance == null || m_Wrapper.m_CatActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CatActionsCallbackInterfaces.Add(instance);
            @CollectClue.started += instance.OnCollectClue;
            @CollectClue.performed += instance.OnCollectClue;
            @CollectClue.canceled += instance.OnCollectClue;
        }

        private void UnregisterCallbacks(ICatActions instance)
        {
            @CollectClue.started -= instance.OnCollectClue;
            @CollectClue.performed -= instance.OnCollectClue;
            @CollectClue.canceled -= instance.OnCollectClue;
        }

        public void RemoveCallbacks(ICatActions instance)
        {
            if (m_Wrapper.m_CatActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICatActions instance)
        {
            foreach (var item in m_Wrapper.m_CatActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CatActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CatActions @Cat => new CatActions(this);

    // Quest
    private readonly InputActionMap m_Quest;
    private List<IQuestActions> m_QuestActionsCallbackInterfaces = new List<IQuestActions>();
    private readonly InputAction m_Quest_TakeQuest;
    public struct QuestActions
    {
        private @PlayerActions m_Wrapper;
        public QuestActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @TakeQuest => m_Wrapper.m_Quest_TakeQuest;
        public InputActionMap Get() { return m_Wrapper.m_Quest; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(QuestActions set) { return set.Get(); }
        public void AddCallbacks(IQuestActions instance)
        {
            if (instance == null || m_Wrapper.m_QuestActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_QuestActionsCallbackInterfaces.Add(instance);
            @TakeQuest.started += instance.OnTakeQuest;
            @TakeQuest.performed += instance.OnTakeQuest;
            @TakeQuest.canceled += instance.OnTakeQuest;
        }

        private void UnregisterCallbacks(IQuestActions instance)
        {
            @TakeQuest.started -= instance.OnTakeQuest;
            @TakeQuest.performed -= instance.OnTakeQuest;
            @TakeQuest.canceled -= instance.OnTakeQuest;
        }

        public void RemoveCallbacks(IQuestActions instance)
        {
            if (m_Wrapper.m_QuestActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IQuestActions instance)
        {
            foreach (var item in m_Wrapper.m_QuestActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_QuestActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public QuestActions @Quest => new QuestActions(this);

    // Sleep
    private readonly InputActionMap m_Sleep;
    private List<ISleepActions> m_SleepActionsCallbackInterfaces = new List<ISleepActions>();
    private readonly InputAction m_Sleep_SleepToEndDay;
    public struct SleepActions
    {
        private @PlayerActions m_Wrapper;
        public SleepActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @SleepToEndDay => m_Wrapper.m_Sleep_SleepToEndDay;
        public InputActionMap Get() { return m_Wrapper.m_Sleep; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SleepActions set) { return set.Get(); }
        public void AddCallbacks(ISleepActions instance)
        {
            if (instance == null || m_Wrapper.m_SleepActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SleepActionsCallbackInterfaces.Add(instance);
            @SleepToEndDay.started += instance.OnSleepToEndDay;
            @SleepToEndDay.performed += instance.OnSleepToEndDay;
            @SleepToEndDay.canceled += instance.OnSleepToEndDay;
        }

        private void UnregisterCallbacks(ISleepActions instance)
        {
            @SleepToEndDay.started -= instance.OnSleepToEndDay;
            @SleepToEndDay.performed -= instance.OnSleepToEndDay;
            @SleepToEndDay.canceled -= instance.OnSleepToEndDay;
        }

        public void RemoveCallbacks(ISleepActions instance)
        {
            if (m_Wrapper.m_SleepActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISleepActions instance)
        {
            foreach (var item in m_Wrapper.m_SleepActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SleepActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SleepActions @Sleep => new SleepActions(this);

    // Tutorials
    private readonly InputActionMap m_Tutorials;
    private List<ITutorialsActions> m_TutorialsActionsCallbackInterfaces = new List<ITutorialsActions>();
    private readonly InputAction m_Tutorials_OpenTutorial;
    public struct TutorialsActions
    {
        private @PlayerActions m_Wrapper;
        public TutorialsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenTutorial => m_Wrapper.m_Tutorials_OpenTutorial;
        public InputActionMap Get() { return m_Wrapper.m_Tutorials; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TutorialsActions set) { return set.Get(); }
        public void AddCallbacks(ITutorialsActions instance)
        {
            if (instance == null || m_Wrapper.m_TutorialsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TutorialsActionsCallbackInterfaces.Add(instance);
            @OpenTutorial.started += instance.OnOpenTutorial;
            @OpenTutorial.performed += instance.OnOpenTutorial;
            @OpenTutorial.canceled += instance.OnOpenTutorial;
        }

        private void UnregisterCallbacks(ITutorialsActions instance)
        {
            @OpenTutorial.started -= instance.OnOpenTutorial;
            @OpenTutorial.performed -= instance.OnOpenTutorial;
            @OpenTutorial.canceled -= instance.OnOpenTutorial;
        }

        public void RemoveCallbacks(ITutorialsActions instance)
        {
            if (m_Wrapper.m_TutorialsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITutorialsActions instance)
        {
            foreach (var item in m_Wrapper.m_TutorialsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TutorialsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TutorialsActions @Tutorials => new TutorialsActions(this);
    public interface IMovementActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IDialogActions
    {
        void OnInteract(InputAction.CallbackContext context);
        void OnContinue(InputAction.CallbackContext context);
    }
    public interface ILootActions
    {
        void OnLootInteraction(InputAction.CallbackContext context);
    }
    public interface IArmouryActions
    {
        void OnAnvilInteraction(InputAction.CallbackContext context);
    }
    public interface IInfirmaryActions
    {
        void OnFirePotInteraction(InputAction.CallbackContext context);
    }
    public interface IStructureActions
    {
        void OnRepair(InputAction.CallbackContext context);
    }
    public interface ICatActions
    {
        void OnCollectClue(InputAction.CallbackContext context);
    }
    public interface IQuestActions
    {
        void OnTakeQuest(InputAction.CallbackContext context);
    }
    public interface ISleepActions
    {
        void OnSleepToEndDay(InputAction.CallbackContext context);
    }
    public interface ITutorialsActions
    {
        void OnOpenTutorial(InputAction.CallbackContext context);
    }
}
